services:
  - type: web
    name: myapp-web
    env: ruby
    plan: free
    buildCommand: ./render-build.sh
    startCommand: bundle exec rails server -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-database

databases:
  - name: myapp-database
    databaseName: myapp_production
    user: myapp_user
    password: auto
    plan: free
