default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Render provides DATABASE_URL automatically for production
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: b_crud_development
  # Optional local username/password
  # username: b_crud
  # password: your_local_password

test:
  <<: *default
  database: b_crud_test

production:
  primary: &primary_production
    <<: *default
    # If DATABASE_URL is set in Render, Rails will use it automatically
    url: <%= ENV['DATABASE_URL'] || "postgres://b_crud:#{ENV['B_CRUD_DATABASE_PASSWORD']}@localhost/b_crud_production" %>

  cache:
    <<: *primary_production
    database: b_crud_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: b_crud_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: b_crud_production_cable
    migrations_paths: db/cable_migrate
